# Generated by Django 3.2.5 on 2021-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0002_auto_20210916_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_main',
            name='marks',
            field=models.IntegerField(max_length=20000, null=True),
        ),
    ]
