# Generated by Django 3.2.5 on 2021-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0003_student_main_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_main',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
