# Generated by Django 3.2.5 on 2021-09-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0006_auto_20210922_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exam',
            new_name='exams',
        ),
    ]
