# Generated by Django 3.2.5 on 2021-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0010_auto_20210922_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_main',
            name='student',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
