# Generated by Django 3.2.5 on 2021-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0011_alter_student_main_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_main',
            name='subject',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
