# Generated by Django 3.2.5 on 2021-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0013_alter_student_main_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_main',
            old_name='class_teacher',
            new_name='class_teacher_name',
        ),
        migrations.AddField(
            model_name='student_main',
            name='class_teacher_username',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
