# Generated by Django 3.2.5 on 2021-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0015_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_teacher',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='class_teacher',
            name='year',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=20000, null=True),
        ),
    ]
