# Generated by Django 3.2.5 on 2021-09-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0016_auto_20210924_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_teacher',
            name='class_teacher',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
