# Generated by Django 3.2.5 on 2021-09-25 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0017_alter_class_teacher_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_year_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_name', models.CharField(max_length=20000, null=True)),
                ('class_teacher_username', models.CharField(max_length=20000, null=True)),
                ('student_name', models.CharField(max_length=20000, null=True)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20000, null=True)),
                ('physics', models.CharField(max_length=20000, null=True)),
                ('chemistry', models.CharField(max_length=20000, null=True)),
                ('maths_1', models.CharField(max_length=20000, null=True)),
                ('maths_2', models.CharField(max_length=20000, null=True)),
                ('pic', models.CharField(max_length=20000, null=True)),
                ('cs', models.CharField(max_length=20000, null=True)),
                ('machanics', models.CharField(max_length=20000, null=True)),
                ('graphics', models.CharField(max_length=20000, null=True)),
                ('bce', models.CharField(max_length=20000, null=True)),
                ('eee', models.CharField(max_length=20000, null=True)),
                ('student_code', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('exam', models.CharField(max_length=20000, null=True)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
    ]
