# Generated by Django 3.2.5 on 2021-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0020_first_year_student_prn'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_year_student',
            name='roll_number',
            field=models.IntegerField(null=True),
        ),
    ]
