# Generated by Django 3.2.5 on 2021-10-02 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marks_app', '0021_first_year_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_year_student',
            name='student_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
