# Generated by Django 3.2.5 on 2021-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20000)),
                ('professor', models.CharField(max_length=20000)),
                ('subject', models.CharField(max_length=2000)),
                ('date', models.DateField(blank=True)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20000)),
                ('year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=20000)),
                ('link', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='lecture_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2000)),
                ('professor', models.CharField(max_length=20000)),
                ('time', models.TimeField()),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20000)),
                ('year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=2000)),
                ('link', models.CharField(max_length=20000)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
