# Generated by Django 3.2.5 on 2021-09-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_class',
            name='status',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
