# Generated by Django 3.2.5 on 2021-08-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_assignments',
            old_name='last_Date',
            new_name='date',
        ),
    ]
