# Generated by Django 3.2.5 on 2021-08-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='slug',
        ),
    ]
