# Generated by Django 3.2.5 on 2021-10-02 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_lecture_class_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_class',
            name='lecture_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
