# Generated by Django 3.2.5 on 2021-08-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20210817_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lecture_class',
        ),
    ]
