# Generated by Django 3.2.5 on 2021-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0007_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture_class',
            name='title',
        ),
        migrations.AddField(
            model_name='lecture_class',
            name='division',
            field=models.CharField(default=1, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_class',
            name='professor',
            field=models.CharField(default=1, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_class',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture_class',
            name='subject',
            field=models.CharField(max_length=2000),
        ),
    ]
