# Generated by Django 3.2.5 on 2021-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0009_alter_lecture_class_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_class',
            name='division',
            field=models.CharField(choices=[('A', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=20000),
        ),
    ]
