# Generated by Django 3.2.5 on 2021-08-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0010_alter_lecture_class_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_class',
            name='division',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=20000),
        ),
        migrations.AlterField(
            model_name='lecture_class',
            name='year',
            field=models.IntegerField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')]),
        ),
    ]
