# Generated by Django 3.2.5 on 2021-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0011_auto_20210819_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_class',
            name='year',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=20000),
        ),
    ]
