# Generated by Django 3.2.5 on 2021-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0012_alter_lecture_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_class',
            name='year',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=2000),
        ),
    ]
