# Generated by Django 3.2.5 on 2021-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_attendance',
            name='lecture_name',
        ),
        migrations.AddField(
            model_name='s_attendance',
            name='lecture_subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
