# Generated by Django 3.2.5 on 2021-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210902_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_attendance',
            name='attendance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='f_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='l_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='lecture_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
