# Generated by Django 3.2.5 on 2021-09-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_s_attendance_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_attendance',
            name='professor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
