# Generated by Django 3.2.5 on 2021-09-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210902_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_attendance',
            name='attendance',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='division',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='f_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='l_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='s_attendance',
            name='lecture_subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
