# Generated by Django 3.2.5 on 2021-09-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20210902_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_attendance',
            name='lecture_subject',
        ),
        migrations.AddField(
            model_name='s_attendance',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
