# Generated by Django 3.2.5 on 2021-09-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_s_attendance_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_attendance',
            name='professor',
        ),
    ]
