# Generated by Django 3.2.5 on 2021-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_s_attendance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_attendance',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
