# Generated by Django 3.2.5 on 2021-09-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_s_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_attendance',
            name='lecture_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
